name: backup

on:
  schedule:
    - cron: '0 16 * * *'   # UTC 16:00 = JST 01:00
  workflow_dispatch: {}

jobs:
  dump:
    runs-on: ubuntu-latest

    env:
      PGHOST: aws-1-ap-northeast-1.pooler.supabase.com
      PGPORT: '5432'
      PGDATABASE: postgres
      PGUSER: postgres.josqeoejhhimsdryxtnv   # ←プロジェクトID付きユーザー
      PGPASSWORD: ${{ secrets.PG_DB_PASSWORD }}  # ← Supabase の「Database password」

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      # SSL 必須で接続確認
      - name: Check connectivity (SSL)
        env:
          PGSSLMODE: require
        run: |
          set -e
          psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -Atc 'select now()'

      # ダンプ（SSL 必須）
      - name: Dump database (SSL)
        env:
          PGSSLMODE: require
        run: |
          set -e
          pg_dump -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -Fc -f backup.dump

      - name: Upload artifact (7days)
        uses: actions/upload-artifact@v4
        with:
          name: pg-backup
          path: backup.dump
          retention-days: 7
