jobs:
  dump:
    runs-on: ubuntu-latest
    env:
      PGUSER:     postgres.josqeoejhhimsdryxtnv
      PGPASSWORD: ${{ secrets.PG_DB_PASSWORD }}
      PGHOST:     aws-1-ap-northeast-1.pooler.supabase.com
      PGPORT:     '5432'
      PGDATABASE: postgres
      PGSSLMODE:  require

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      - name: Dump database
        run: |
          set -e
          pg_dump -Fc -f backup.dump

      - name: Upload artifact (7days)
        uses: actions/upload-artifact@v4
        with:
          name: pg-backup
          path: backup.dump
          retention-days: 7
