name: backup

on:
  schedule:
    - cron: '0 16 * * *'   # UTC16:00 = JST 01:00
  workflow_dispatch: {}     # 手動実行ボタンも残す

jobs:
  dump:
    runs-on: ubuntu-latest
    env:
      # ← GitHub Secrets に作った「PG_URL_RO」を渡す
      PGURL: ${{ secrets.PG_URL_RO }}

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      # ── ここが「一時デバッグ」ステップ（確認できたら削除OK） ──
      - name: Check pg connectivity (temporary)
        run: |
          set -e
          psql --version
          pg_isready -d "$PGURL" -t 10 || true
          # 実接続テスト（Secretsはマスクされるが echo はしない）
          psql "$PGURL" -Atc 'select now()' || true

      - name: Dump database
        run: |
          set -e
          pg_dump --format=custom --file=backup.dump "$PGURL"

      - name: Upload artifact (7days)
        uses: actions/upload-artifact@v4
        with:
          name: pg-backup
          path: backup.dump
          retention-days: 7
