name: backup

on:
  schedule:
    - cron: '0 16 * * *'          # UTC 16:00 = JST 01:00
  workflow_dispatch: {}

jobs:
  dump:
    runs-on: ubuntu-latest
    env:
      PGURL: ${{ secrets.PG_URL_RO }}

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      # 一時デバッグ（接続できるか確認）
      - name: Check pg connectivity (temporary)
        run: |
          set -e
          psql --version
          pg_isready -d "$PGURL" -t 10 || true
          psql "$PGURL" -Atc 'select now()' || true

      - name: Dump database
        run: |
          set -e
          pg_dump --format=custom --file=backup.dump "$PGURL"

      - name: Upload artifact (7days)
        uses: actions/upload-artifact@v4
        with:
          name: pg-backup
          path: backup.dump
          retention-days: 7
