name: backup

on:
  schedule:
    - cron: '0 16 * * *'   # UTC16:00 = JST 01:00
  workflow_dispatch: {}

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      # ここでユーザー名をベタ書きして確実に検証
      - name: Check connectivity (SSL)
        env:
          PGSSLMODE: require
          PGPASSWORD: ${{ secrets.PG_DB_PASSWORD }}   # ← Supabase の「Database password」
        run: |
          set -e
          psql \
            -h aws-1-ap-northeast-1.pooler.supabase.com \
            -p 5432 \
            -d postgres \
            -U postgres.josqeoejhhimsdryxtnv \
            -Atc 'select current_user, now()'

      - name: Dump database (SSL)
        env:
          PGSSLMODE: require
          PGPASSWORD: ${{ secrets.PG_DB_PASSWORD }}
        run: |
          set -e
          pg_dump \
            -h aws-1-ap-northeast-1.pooler.supabase.com \
            -p 5432 \
            -d postgres \
            -U postgres.josqeoejhhimsdryxtnv \
            -Fc -f backup.dump

      - name: Upload artifact (7days)
        uses: actions/upload-artifact@v4
        with:
          name: pg-backup
          path: backup.dump
          retention-days: 7
