name: backup
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch: {}

jobs:
  dump:
    runs-on: ubuntu-latest
    env:
      DB_URL: "${{ secrets.SUPABASE_DB_URL }}"  # ← URI 丸ごと

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      - name: Check connectivity (SSL)
        run: |
          set -e
          psql "$DB_URL" -c '\conninfo'
          psql "$DB_URL" -Atc 'select current_user, now()'

      - name: Dump database (SSL)
        run: |
          set -e
          pg_dump --clean --if-exists --format=custom --file=backup.dump "$DB_URL"

      - name: Upload artifact (7days)
        uses: actions/upload-artifact@v4
        with:
          name: pg-backup
          path: backup.dump
          retention-days: 7
