name: backup

on:
  schedule:
    - cron: '0 16 * * *'   # UTC16:00 = JST 01:00
  workflow_dispatch: {}

jobs:
  dump:
    runs-on: ubuntu-latest
    env:
      PGURL: ${{ secrets.PG_URL_RO }}   # ← 末尾に ?sslmode は付けない

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      - name: Dump database
        run: |
          set -e
          pg_dump --format=custom --file=backup.dump "${PGURL}?sslmode=require"

      - name: Upload artifact (7days)
        uses: actions/upload-artifact@v4
        with:
          name: pg-backup
          path: backup.dump
          retention-days: 7
