on:
  schedule:
    - cron: '*/5 * * * *'     # 5分おき（UTC）
  workflow_dispatch: {}
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /healthz
        run: |
          set -e
          code=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.API_URL }}/healthz")
          echo "HTTP $code"
          test "$code" = "200"     # 200以外ならジョブ失敗 -> 赤く目立つ
